package com.example.mynativeapp1.ui.theme

import androidx.compose.ui.graphics.Color

val SkyPrimary = Color(0xFF0284C7)
val SkyOnPrimary = Color(0xFFFFFFFF)
val SkySecondary = Color(0xFF0EA5E9)
val SkyOnSecondary = Color(0xFF0F172A)
val SkyTertiary = Color(0xFFF59E0B)
val SkyOnTertiary = Color(0xFF0F172A)
val SkyBackground = Color(0xFFF0F9FF)
val SkyOnBackground = Color(0xFF0F172A)
val SkySurface = Color(0xFFFFFFFF)
val SkyOnSurface = Color(0xFF0F172A)
val SkyOnSurfaceVariant = Color(0xFF475569)
val SkySurfaceVariant = Color(0xFFEFF7FB)
val SkyOutline = Color(0xFFE0F0F8)

val SkyPrimaryDark = Color(0xFF38BDF8)
val SkyOnPrimaryDark = Color(0xFF0F172A)
val SkySecondaryDark = Color(0xFF7DD3FC)
val SkyOnSecondaryDark = Color(0xFF0F172A)
val SkyTertiaryDark = Color(0xFFFBBF24)
val SkyOnTertiaryDark = Color(0xFF0F172A)
val SkyBackgroundDark = Color(0xFF0F172A)
val SkyOnBackgroundDark = Color(0xFFF8FAFC)
val SkySurfaceDark = Color(0xFF1E293B)
val SkyOnSurfaceDark = Color(0xFFF8FAFC)
val SkyOnSurfaceVariantDark = Color(0xFF94A3B8)
val SkySurfaceVariantDark = Color(0xFF334155)
val SkyOutlineDark = Color(0xFF475569)
